REPORT Z_CADASTROMATERIAL.

* DEFINI ESTRUTURA
DATA: BEGIN OF PRODUTO,
        DESCRICAO(50) TYPE C,
        CODIGO(2)     TYPE N,
      END OF PRODUTO.

* TABELA PRODUTOS COM O TIPO DA ESTRUTURA PRODUTO
DATA: PRODUTOS LIKE TABLE OF PRODUTO.


PRODUTO-CODIGO = 31.
PRODUTO-DESCRICAO = 'CARRO'.

APPEND PRODUTO TO PRODUTOS.

PRODUTO-CODIGO = 41.
PRODUTO-DESCRICAO = 'NOTEBOOK'.

APPEND PRODUTO TO PRODUTOS.

PRODUTO-CODIGO = 50.
PRODUTO-DESCRICAO = 'MOTO'.

APPEND PRODUTO TO PRODUTOS.

WRITE:
/ 'CODIGO', PRODUTOS[ 1 ]-CODIGO,
/ 'DESCRICAO', PRODUTOS[ 1 ]-DESCRICAO.

SKIP.

WRITE:
/ 'CODIGO', PRODUTOS[ 2 ]-CODIGO,
/ 'DESCRICAO', PRODUTOS[ 2 ]-DESCRICAO.

SKIP.

WRITE:
/ 'CODIGO', PRODUTOS[ 3 ]-CODIGO,
/ 'DESCRICAO', PRODUTOS[ 3 ]-DESCRICAO.
