*&---------------------------------------------------------------------*
*& Report z_exercicio12
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT Z_EXERCICIO12.


*DECLARA A ESTRUTURA

DATA:BEGIN OF TRANSPORTE,
       CODIGO          TYPE STRING,
       DESCRICAO       TYPE STRING,
       CAPACIDADE      TYPE I,
       DATA_FABRICACAO TYPE D,
       MARCA           TYPE STRING,
       COR             TYPE STRING,
     END OF TRANSPORTE.

*DECLARA A TABELA COM O TIPO DA ESTRUTURA

DATA: TRANSPORTES LIKE TABLE OF TRANSPORTE.


TRANSPORTE-CODIGO = 'T001'.
TRANSPORTE-DESCRICAO = 'Carro de Passageiros'.
TRANSPORTE-CAPACIDADE = 5.
TRANSPORTE-DATA_FABRICACAO = '20230101'.
TRANSPORTE-MARCA = 'CarBrand'.
TRANSPORTE-COR = 'Azul'.
INSERT TRANSPORTE INTO TABLE TRANSPORTES.

TRANSPORTE-CODIGO = 'T002'.
TRANSPORTE-DESCRICAO = 'Caminhão de Carga'.
TRANSPORTE-CAPACIDADE = 10000.
TRANSPORTE-DATA_FABRICACAO = '20230201'.
TRANSPORTE-MARCA = 'TruckCo'.
TRANSPORTE-COR = 'Vermelho'.

APPEND TRANSPORTE TO TRANSPORTES.


TRANSPORTE-CODIGO = 'T003'.
TRANSPORTE-DESCRICAO = 'Bicicleta'.
TRANSPORTE-CAPACIDADE = 1.
TRANSPORTE-DATA_FABRICACAO = '20230301'.
TRANSPORTE-MARCA = 'BikeBrand'.
TRANSPORTE-COR = 'Verde'.

APPEND TRANSPORTE TO TRANSPORTES.


LOOP AT TRANSPORTES INTO TRANSPORTE.
  WRITE: / 'Código:', TRANSPORTE-CODIGO,
         / 'Descrição:', TRANSPORTE-DESCRICAO,
         / 'Capacidade:', TRANSPORTE-CAPACIDADE,
         / 'Data de Fabricação:', TRANSPORTE-DATA_FABRICACAO,
         / 'Marca:', TRANSPORTE-MARCA,
         / 'Cor:', TRANSPORTE-COR.
ENDLOOP.
