REPORT Z_SEARCH_AIRLINE_COMPANY.

TYPES: BEGIN OF TY_SCARR,
         MANDT    TYPE SCARR-MANDT,
         CARRID   TYPE SCARR-CARRID,
         CARRNAME TYPE SCARR-CARRNAME,
         CURRCODE TYPE SCARR-CURRCODE,
       END OF TY_SCARR.

DATA:
  LT_SCARR   TYPE TABLE OF TY_SCARR,
  WA_SCARR   TYPE TY_SCARR,
  LV_PATTERN TYPE STRING.

SELECTION-SCREEN BEGIN OF BLOCK BlockOne
  WITH FRAME TITLE TEXT-001.

  PARAMETERS: P_CARRID TYPE SCARR-CARRID,
              P_CARRNM TYPE SCARR-CARRNAME.

SELECTION-SCREEN END OF BLOCK BlockOne.

LV_PATTERN = '%' && P_CARRNM && '%'.

SELECT MANDT, CARRID, CARRNAME, CURRCODE
  INTO TABLE @LT_SCARR
  FROM SCARR
 WHERE CARRID = @P_CARRID
    OR CARRNAME LIKE @LV_PATTERN.

IF SY-SUBRC = 0.
  LOOP AT LT_SCARR INTO WA_SCARR.
    WRITE: / 'Mandante: ', WA_SCARR-MANDT,
           / 'Id:       ', WA_SCARR-CARRID,
           / 'Cia Aérea:', WA_SCARR-CARRNAME,
           / 'Cod.Moeda:', WA_SCARR-CURRCODE.
  ENDLOOP.
ENDIF.
