*&---------------------------------------------------------------------*
*& Include          ZINCLUDE_DROPDOWNOPERACOES
*&---------------------------------------------------------------------*

FORM DROPDOWNOPERACOES USING OPERACAO TYPE C.

  TYPES: BEGIN OF TY_OPERACOES,
      ID TYPE I,
      DESCRICAO TYPE C LENGTH 10,
  END OF TY_OPERACOES.


  DATA: IT_OPERACOES TYPE STANDARD TABLE OF TY_OPERACOES,
        WA_OPERACOES TYPE TY_OPERACOES.

  DATA: G_ID      TYPE VRM_ID,
        IT_VALUES TYPE VRM_VALUES,
        WA_VALUES LIKE LINE OF IT_VALUES.




  SELECT ID ,DESCRICAO FROM ZCALOPTAB606 INTO TABLE @IT_OPERACOES.

  LOOP AT IT_OPERACOES INTO WA_OPERACOES.

    WA_VALUES-KEY = '' && WA_OPERACOES-ID && ''.
    WA_VALUES-TEXT = WA_OPERACOES-DESCRICAO.
    APPEND WA_VALUES TO IT_VALUES.
    CLEAR WA_VALUES.
  ENDLOOP.



  G_ID = 'OPERACAO'.

  CALL FUNCTION 'VRM_SET_VALUES'
    EXPORTING
      ID     = G_ID
      VALUES = IT_VALUES.

ENDFORM.
